language: node_js
node_js: '8'
notifications:
  email:
    on_success: never
    on_failure: always 
branches:
  only: master
jobs:
  include:
    - stage: lint
      before_install:
         - npm config set package-lock false
      install:
        - cd ./gui-electron
        - npm i
      script: 
        - npm run lint
    - stage: test
      name: "GUI Linux"
      os:
        - linux
      before_install:
         - npm config set package-lock false
      install:
        - cd ./gui-electron
        - npm i
      script: 
        - npm run test:coverage | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - name: "GUI Windows"
      os:
        - windows
      before_install:
         - npm config set package-lock false
      install:
        - cd ./gui-electron
        - npm i
      script: 
        - npm run test
    - stage: deploy
      name: "Create windows application"
      os:
        - windows
      before_install:
         - npm config set package-lock false
      install:
        - cd ./gui-electron
        - npm i
      script:
        - npm run build-update
        - npm run build-win-app